import '../styles/globals.css'
import Head from 'next/head'

import DarkModeProvider from '@providers/DarkMode'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>WizeBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <DarkModeProvider>
          <Component {...pageProps} />
        </DarkModeProvider>
      </body>
    </>
  )
}

export default MyApp
