import '../styles/globals.css'
import Head from 'next/head'

import DarkModeProvider from '@providers/DarkMode'
import AccountProvider from '@providers/Account'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>WizeBank</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AccountProvider>
          <DarkModeProvider>
            <Component {...pageProps} />
          </DarkModeProvider>
        </AccountProvider>
      </main>
    </>
  )
}

export default MyApp
